# Streamlit Secrets 配置文件
# 這個文件包含應用程序所需的機密 API 密鑰

# DeepSeek API 密鑰
DEEPSEEK_API_KEY = "sk-6ae04d6789f94178b4053d2c42650b6c"

# CoinMarketCap API 密鑰
COINMARKETCAP_API_KEY = "b54bcf4d-1bca-4e8e-9a24-22ff2c3d462c"

# OpenAI API 密鑰 (需要替換為您的真實 API 密鑰)
OPENAI_API_KEY = "sk-your-openai-api-key" 